# Example environment configuration

GOOGLE_CLOUD_PROJECT: your-gcp-project-id
GOOGLE_CLOUD_LOCATION: us-central1
GOOGLE_GENAI_USE_VERTEXAI: "true"

DATA_STORE_ID: projects/your-gcp-project-id/locations/global/collections/default_collection/dataStores/your-datastore-id

MAESTRO_AGENT_RESOURCE_NAME: projects/your-gcp-project-id/locations/us-central1/reasoningEngines/your-maestro-agent-id 