GOOGLE_CLOUD_PROJECT: menovibe
GOOGLE_CLOUD_LOCATION: us-central1
GOOGLE_GENAI_USE_VERTEXAI: "true"

DATA_STORE_ID: projects/menovibe/locations/global/collections/default_collection/dataStores/menoguide-db

MAESTRO_AGENT_RESOURCE_NAME: projects/39073596935/locations/us-central1/reasoningEngines/6957190611078217728